/**
 ******************************************************************************
 * @file      syscalls.c
 * @author    Auto-generated by STM32CubeIDE
 * @brief     STM32CubeIDE Minimal System calls file
 *
 *            For more information about which c-functions
 *            need which of these lowlevel functions
 *            please consult the Newlib libc-manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <sys/stat.h>
#include <stdlib.h>
#include <errno.h>
#include <stdio.h>
#include <signal.h>
#include <time.h>
#include <sys/time.h>
#include <sys/times.h>

/* Variables */
extern int __io_putchar(int ch) __attribute__((weak));
extern int __io_getchar(void) __attribute__((weak));

char *__env[1] = { 0 };
char **environ = __env;

/* Functions */
void initialise_monitor_handles()
{
}

int _getpid(void)
{
	return 1;
}

int _kill(int pid   __attribute__((unused)), int sig   __attribute__((unused)))
{
	errno = EINVAL;
	return -1;
}

void _exit (int status)
{
	_kill(status, -1);
	while (1) {}		/* Make sure we hang here */
}

__attribute__((weak)) int _read(int file  __attribute__((unused)), char *ptr, int len)
{
	int DataIdx;

	for (DataIdx = 0; DataIdx < len; DataIdx++)
	{
		*ptr++ = __io_getchar();
	}

return len;
}

__attribute__((weak)) int _write(int file  __attribute__((unused)), char *ptr, int len)
{
	int DataIdx;

	for (DataIdx = 0; DataIdx < len; DataIdx++)
	{
		__io_putchar(*ptr++);
	}
	return len;
}

int _close(int file  __attribute__((unused)))
{
	return -1;
}


int _fstat(int file  __attribute__((unused)), struct stat *st)
{
	st->st_mode = S_IFCHR;
	return 0;
}

int _isatty(int file  __attribute__((unused)))
{
	return 1;
}

int _lseek(int file  __attribute__((unused)), int ptr  __attribute__((unused)), int dir  __attribute__((unused)))
{
	return 0;
}

int _open(char *path  __attribute__((unused)), int flags  __attribute__((unused)), ...)
{
	/* Pretend like we always fail */
	return -1;
}

int _wait(int *status  __attribute__((unused)))
{
	errno = ECHILD;
	return -1;
}

int _unlink(char *name  __attribute__((unused)))
{
	errno = ENOENT;
	return -1;
}

int _times(struct tms *buf  __attribute__((unused)))
{
	return -1;
}

int _stat(char *file  __attribute__((unused)), struct stat *st)
{
	st->st_mode = S_IFCHR;
	return 0;
}

int _link(char *old  __attribute__((unused)), char *new  __attribute__((unused)))
{
	errno = EMLINK;
	return -1;
}

int _fork(void)
{
	errno = EAGAIN;
	return -1;
}

int _execve(char *name  __attribute__((unused)), char **argv  __attribute__((unused)), char **env  __attribute__((unused)))
{
	errno = ENOMEM;
	return -1;
}
